# Generated by Django 6.0.3 on 2026-03-25 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Datum')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Grund')),
            ],
            options={
                'verbose_name': 'Gesperrter Tag',
                'verbose_name_plural': 'Gesperrte Tage',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_advance_days', models.PositiveIntegerField(default=14, help_text='Wie viele Tage im Voraus muss gebucht werden?', verbose_name='Mindestvorlauf (Tage)')),
                ('max_booking_months', models.PositiveIntegerField(default=6, help_text='Wie weit in die Zukunft darf gebucht werden?', verbose_name='Maximaler Buchungszeitraum (Monate)')),
                ('contact_name', models.CharField(default='Peter Fedders / Eike Nonhoff', max_length=200, verbose_name='Ansprechpartner')),
                ('contact_email', models.EmailField(default='sportheim@westfalia-osterwick.de', max_length=254, verbose_name='Kontakt-E-Mail')),
            ],
            options={
                'verbose_name': 'Einstellungen',
                'verbose_name_plural': 'Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Name / Gruppe')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('purpose', models.CharField(max_length=300, verbose_name='Anlass / Zweck')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('date', models.DateField(verbose_name='Datum')),
                ('start_time', models.TimeField(verbose_name='Von')),
                ('end_time', models.TimeField(verbose_name='Bis')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('confirmed', 'Bestätigt'), ('rejected', 'Abgelehnt')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_note', models.TextField(blank=True, help_text='Nur für Admin und Verwaltung sichtbar', verbose_name='Interne Notiz (Admin)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Buchung',
                'verbose_name_plural': 'Buchungen',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
