# Generated by Django 6.0.3 on 2026-03-25 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Stornierungstoken'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('confirmed', 'Bestätigt'), ('rejected', 'Abgelehnt'), ('cancelled', 'Storniert')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
